spring.application.name=stocksmart

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/stocksmart
spring.datasource.username=root
spring.datasource.password=#1234aru*aashirwad

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true